name = "watkookjemenu"
compatibility_date = "2025-01-01"
pages_build_output_dir = "public"

[vars]
SITE_URL = "https://watkookjemenu.nl"

[[kv_namespaces]]
binding = "PRINT_ORDER_DEDUPE"
id = "d2a4b4a757544dc5aa2f106f83fcf0c2"
preview_id = "7408ce4571d24f2986eae57ee1a8ada7"
